# Values taken from https://gist.github.com/graydon/11198540 (python obj in format W Lon, S Lat, E Lon, N Lat)
# Formatted here as yaml: S Lat, N Lat, W Lon, E Lon to match osm: http://wiki.openstreetmap.org/wiki/Bounding_Box

af: [29.318572496, 38.4862816432, 60.5284298033, 75.1580277851]
ao: [-17.9306364885, -4.43802336998, 11.6400960629, 24.0799052263]
al: [39.624997667, 42.6882473822, 19.3044861183, 21.0200403175]
ae: [22.4969475367, 26.055464179, 51.5795186705, 56.3968473651]
ar: [-55.25, -21.8323104794, -73.4154357571, -53.628348965]
am: [38.7412014837, 41.2481285671, 43.5827458026, 46.5057198423]
aq: [-90.0, -63.2706604895, -180.0, 180.0]
tf: [-49.775, -48.625, 68.72, 70.56]
au: [-43.6345972634, -10.6681857235, 113.338953078, 153.569469029]
at: [46.4318173285, 49.0390742051, 9.47996951665, 16.9796667823]
az: [38.2703775091, 41.8606751572, 44.7939896991, 50.3928210793]
bi: [-4.49998341229, -2.34848683025, 29.0249263852, 30.752262811]
be: [49.5294835476, 51.4750237087, 2.51357303225, 6.15665815596]
bj: [6.14215770103, 12.2356358912, 0.772335646171, 3.79711225751]
bf: [9.61083486576, 15.1161577418, -5.47056494793, 2.17710778159]
bd: [20.670883287, 26.4465255803, 88.0844222351, 92.6727209818]
bg: [41.2344859889, 44.2349230007, 22.3805257504, 28.5580814959]
bs: [23.71, 27.04, -78.98, -77.0]
ba: [42.65, 45.2337767604, 15.7500260759, 19.59976]
by: [51.3195034857, 56.1691299506, 23.1994938494, 32.6936430193]
bz: [15.8869375676, 18.4999822047, -89.2291216703, -88.1068129138]
bo: [-22.8729187965, -9.76198780685, -69.5904237535, -57.4983711412]
br: [-33.7683777809, 5.24448639569, -73.9872354804, -34.7299934555]
bn: [4.007636827, 5.44772980389, 114.204016555, 115.450710484]
bt: [26.7194029811, 28.2964385035, 88.8142484883, 92.1037117859]
bw: [-26.8285429827, -17.6618156877, 19.8954577979, 29.4321883481]
cf: [2.2676396753, 11.1423951278, 14.4594071794, 27.3742261085]
ca: [41.6751050889, 83.23324, -140.99778, -52.6480987209]
ch: [45.7769477403, 47.8308275417, 6.02260949059, 10.4427014502]
cl: [-55.61183, -17.5800118954, -75.6443953112, -66.95992]
cn: [18.197700914, 53.4588044297, 73.6753792663, 135.026311477]
ci: [4.33828847902, 10.5240607772, -8.60288021487, -2.56218950033]
cm: [1.72767263428, 12.8593962671, 8.48881554529, 16.0128524106]
cd: [-13.2572266578, 5.25608775474, (12.1823368669, 31.1741492042]
cg: [-5.03798674888, 3.72819651938, (11.0937728207, 18.4530652198]
co: [-4.29818694419, 12.4373031682, -78.9909352282, -66.8763258531]
cr: [8.22502798099, 11.2171192489, -85.94172543, -82.5461962552]
cu: [19.8554808619, 23.1886107447, -84.9749110583, -74.1780248685]
cy: [34.5718694118, 35.1731247015, 32.2566671079, 34.0048808123]
cz: [48.5553052842, 51.1172677679, 12.2401111182, 18.8531441586]
de: [47.3024876979, 54.983104153, 5.98865807458, 15.0169958839]
dj: [10.9268785669, 12.6996385767, 41.66176, 43.3178524107]
dk: [54.8000145534, 57.730016588, 8.08997684086, 12.6900061378]
do: [17.598564358, 19.8849105901, -71.9451120673, -68.3179432848]
dz: [19.0573642034, 37.1183806422, -8.68439978681, 11.9995056495]
ec: [-4.95912851321, 1.3809237736, -80.9677654691, -75.2337227037]
eg: [22.0, 31.58568, 24.70007, 36.86623]
er: [12.4554157577, 17.9983074, 36.3231889178, 43.0812260272]
es: [35.946850084, 43.7483377142, -9.39288367353, 3.03948408368]
ee: [57.4745283067, 59.6110903998, 23.3397953631, 28.1316992531]
et: [3.42206, 14.95943, 32.95418, 47.78942]
fi: [59.846373196, 70.1641930203, 20.6455928891, 31.5160921567]
fj: [-18.28799, -16.0208822567, -180.0, 180.0]
fk: [-52.3, -51.1, -61.2, -57.75]
fr: [2.05338918702, 51.1485061713, -54.5247541978, 9.56001631027]
ga: [-3.97882659263, 2.32675751384, 8.79799563969, 14.4254557634]
gb: [49.959999905, 58.6350001085, -7.57216793459, 1.68153079591]
ge: [41.0644446885, 43.553104153, 39.9550085793, 46.6379081561]
gh: [4.71046214438, 11.0983409693, -3.24437008301, 1.0601216976]
gn: [7.3090373804, 12.5861829696, -15.1303112452, -7.83210038902]
gm: [13.1302841252, 13.8764918075, -16.8415246241, -13.8449633448]
gw: [11.0404116887, 12.6281700708, -16.6774519516, -13.7004760401]
gq: [1.01011953369, 2.28386607504, 9.3056132341, 11.285078973]
gr: [34.9199876979, 41.8269046087, 20.1500159034, 26.6041955909]
gl: [60.03676, 83.64513, -73.297, -12.20855]
gt: [13.7353376327, 17.8193260767, -92.2292486234, -88.2250227526]
gy: [1.26808828369, 8.36703481692, -61.4103029039, -56.5393857489]
hn: [12.9846857772, 16.0054057886, -89.3533259753, -83.147219001]
hr: [42.47999136, 46.5037509222, 13.6569755388, 19.3904757016]
ht: [18.0309927434, 19.9156839055, -74.4580336168, -71.6248732164]
hu: [45.7594811061, 48.6238540716, 16.2022982113, 22.710531447]
id: [-10.3599874813, 5.47982086834, 95.2930261576, 141.03385176]
in: [7.96553477623, 35.4940095078, 68.1766451354, 97.4025614766]
ie: [51.6693012559, 55.1316222195, -9.97708574059, -6.03298539878]
ir: [25.0782370061, 39.7130026312, 44.1092252948, 63.3166317076]
iq: [29.0990251735, 37.3852635768, 38.7923405291, 48.5679712258]
is: [63.4963829617, 66.5267923041, -24.3261840479, -13.609732225]
il: [29.5013261988, 33.2774264593, 34.2654333839, 35.8363969256]
it: [36.619987291, 47.1153931748, 6.7499552751, 18.4802470232]
jm: [17.7011162379, 18.5242184514, -78.3377192858, -76.1996585761]
jo: [29.1974946152, 33.3786864284, 34.9226025734, 39.1954683774]
jp: [31.0295791692, 45.5514834662, 129.408463169, 145.543137242]
kz: [40.6623245306, 55.3852501491, 46.4664457538, 87.3599703308]
ke: [-4.67677, 5.506, 33.8935689697, 41.8550830926]
kg: [39.2794632025, 43.2983393418, 69.464886916, 80.2599902689]
kh: [10.4865436874, 14.5705838078, 102.3480994, 107.614547968]
kr: [34.3900458847, 38.6122429469, 126.117397903, 129.468304478]
kw: [28.5260627304, 30.0590699326, 46.5687134133, 48.4160941913]
la: [13.88109101, 22.4647531194, 100.115987583, 107.564525181]
lb: [33.0890400254, 34.6449140488, 35.1260526873, 36.6117501157]
lr: [4.35575511313, 8.54105520267, -11.4387794662, -7.53971513511]
ly: [19.58047, 33.1369957545, 9.31941084152, 25.16482]
lk: [5.96836985923, 9.82407766361, 79.6951668639, 81.7879590189]
ls: [-30.6451058896, -28.6475017229, 26.9992619158, 29.3251664568]
lt: [53.9057022162, 56.3725283881, 21.0558004086, 26.5882792498]
lu: [49.4426671413, 50.1280516628, 5.67405195478, 6.24275109216]
lv: [55.61510692, 57.9701569688, 21.0558004086, 28.1767094256]
ma: [21.4207341578, 35.7599881048, -17.0204284327, -1.12455115397]
md: [45.4882831895, 48.4671194525, 26.6193367856, 30.0246586443]
mg: [-25.6014344215, -12.0405567359, 43.2541870461, 50.4765368996]
mx: [14.5388286402, 32.72083, -117.12776, -86.811982388]
mk: [40.8427269557, 42.3202595078, 20.46315, 22.9523771502]
ml: [10.0963607854, 24.9745740829, -12.1707502914, 4.27020999514]
mm: [9.93295990645, 28.335945136, 92.3032344909, 101.180005324]
me: [41.87755, 43.52384, 18.45, 20.3398]
mn: [41.5974095729, 52.0473660345, 87.7512642761, 119.772823928]
mz: [-26.7421916643, -10.3170960425, 30.1794812355, 40.7754752948]
mr: [14.6168342147, 27.3957441269, -17.0634232243, -4.92333736817]
mw: [-16.8012997372, -9.23059905359, 32.6881653175, 35.7719047381]
my: [0.773131415201, 6.92805288332, 100.085756871, 119.181903925]
na: [-29.045461928, -16.9413428687, 11.7341988461, 25.0844433937]
nc: [-22.3999760881, -20.1056458473, 164.029605748, 167.120011428]
ne: [11.6601671412, 23.4716684026, 0.295646396495, 15.9032466977]
ng: [4.24059418377, 13.8659239771, 2.69170169436, 14.5771777686]
ni: [10.7268390975, 15.0162671981, -87.6684934151, -83.147219001]
nl: [50.803721015, 53.5104033474, 3.31497114423, 7.09205325687]
no: [58.0788841824, 80.6571442736, 4.99207807783, 31.29341841]
np: [26.3978980576, 30.4227169866, 80.0884245137, 88.1748043151]
nz: [-46.641235447, -34.4506617165, 166.509144322, 178.517093541]
om: [16.6510511337, 26.3959343531, 52.0000098, 59.8080603372]
pk: [23.6919650335, 37.1330309108, 60.8742484882, 77.8374507995]
pa: [7.2205414901, 9.61161001224, -82.9657830472, -77.2425664944]
pe: [-18.3479753557, -0.0572054988649, -81.4109425524, -68.6650797187]
ph: [5.58100332277, 18.5052273625, 117.17427453, 126.537423944]
pg: [-10.6524760881, -2.50000212973, 141.000210403, 156.019965448]
pl: [49.0273953314, 54.8515359564, 14.0745211117, 24.0299857927]
pr: [17.946553453, 18.5206011011, -67.2424275377, -65.5910037909]
kp: [37.669070543, 42.9853868678, 124.265624628, 130.780007359]
pt: [36.838268541, 42.280468655, -9.52657060387, -6.3890876937]
py: [-27.5484990374, -19.3427466773, -62.6850571357, -54.2929595608]
qa: [24.5563308782, 26.1145820175, 50.7439107603, 51.6067004738]
ro: [43.6884447292, 48.2208812526, 20.2201924985, 29.62654341]
ru: [41.151416124, 81.2504, -180.0, 180.0]
rw: [-2.91785776125, -1.13465911215, 29.0249263852, 30.8161348813]
sa: [16.3478913436, 32.161008816, 34.6323360532, 55.6666593769]
sd: [8.61972971293, 22.0, 21.93681, 38.4100899595]
ss: [3.50917, 12.2480077571, 23.8869795809, 35.2980071182]
sn: [12.332089952, 16.5982636581, -17.6250426905, -11.4678991358]
sb: [-10.8263672828, -6.59933847415, 156.491357864, 162.398645868]
sl: [6.78591685631, 10.0469839543, -13.2465502588, -10.2300935531]
sv: [13.1490168319, 14.4241327987, -90.0955545723, -87.7235029772]
so: [-1.68325, 12.02464, 40.98105, 51.13387]
rs: [42.2452243971, 46.1717298447, 18.82982, 22.9860185076]
sr: [1.81766714112, 6.0252914494, -58.0446943834, -53.9580446031]
sk: [47.7584288601, 49.5715740017, 16.8799829444, 22.5581376482]
si: [45.4523163926, 46.8523859727, 13.6981099789, 16.5648083839]
se: [55.3617373725, 69.1062472602, 11.0273686052, 23.9033785336]
sz: [-27.2858794085, -25.660190525, 30.6766085141, 32.0716654803]
sy: [32.312937527, 37.2298725449, 35.7007979673, 42.3495910988]
td: [7.42192454674, 23.40972, 13.5403935076, 23.88689]
tg: [5.92883738853, 11.0186817489, -0.0497847151599, 1.86524051271]
th: [5.69138418215, 20.4178496363, 97.3758964376, 105.589038527]
tj: [36.7381712916, 40.9602133245, 67.4422196796, 74.9800024759]
tm: [35.2706639674, 42.7515510117, 52.5024597512, 66.5461503437]
tl: [-9.39317310958, -8.27334482181, 124.968682489, 127.335928176]
tt: [10.0, 10.89, -61.95, -60.895]
tn: [30.3075560572, 37.3499944118, 7.52448164229, 11.4887874691]
tr: [35.8215347357, 42.1414848903, 26.0433512713, 44.7939896991]
tw: [21.9705713974, 25.2954588893, 120.106188593, 121.951243931]
tz: [-11.7209380022, -0.95, 29.3399975929, 40.31659]
ug: [-1.44332244223, 4.24988494736, 29.5794661801, 35.03599]
ua: [44.3614785833, 52.3350745713, 22.0856083513, 40.0807890155]
uy: [-34.9526465797, -30.1096863746, -58.4270741441, -53.209588996]
us: [18.91619, 71.3577635769, -171.791110603, -66.96466]
uz: [37.1449940049, 45.5868043076, 55.9289172707, 73.055417108]
ve: [0.724452215982, 12.1623070337, -73.3049515449, -59.7582848782]
vn: [8.59975962975, 23.3520633001, 102.170435826, 109.33526981]
vu: [-16.5978496233, -14.6264970842, 166.629136998, 167.844876744]
ps: [31.3534353704, 32.5325106878, 34.9274084816, 35.5456653175]
ye: [12.5859504257, 19.0000033635, 42.6048726743, 53.1085726255]
za: [-34.8191663551, -22.0913127581, 16.3449768409, 32.830120477]
zm: [-17.9612289364, -8.23825652429, 21.887842645, 33.4856876971]
zw: [-22.2716118303, -15.5077869605, 25.2642257016, 32.8498608742]
